<script>
    import { Heading, Li, List } from "flowbite-svelte";
</script>
<div class="flex flex-col  px-5 bg-opacity-10">
<br>
<Heading class="text-center">Bibliography</Heading>
<br>
<List class="max-w-none pl-5 mt-2 space-y-1" list="none">
    <Li class="py-2">Accardo, A. L., Pontes, N. M. H., & Pontes, M. C. F. (2023). Greater Physical Activity is Associated with Lower Rates of Anxiety and Depression Among Autistic and ADHD Youth: National Survey of Children’s Health 2016–2020. *Journal of Autism and Developmental Disorders*. https://doi.org/10.1007/s10803-023-06117-0</Li>
    <Li class="py-2">Adami, C., Aznar, J. M., Balic, M. G., Bontognali, M., Muroni, R., Davitt, S., . . . Rundqvist, T. v. d. W., Tycho. (2022). *AUTJUDO: A Handbook on how to teach Judo to people with Autistic Spectrum Disorder* (B. L. James Mulroy, Ed.)  https://cdn.judomanager.com/files/web/4/Autjudo%20Best%20Practice%20Handbook%20v1.0%20en.pdf</Li>
    <Li class="py-2">Autism Awareness Australia (2021). *Autism signs in children*. https://www.autismawareness.com.au/understanding-autism/signs-children</Li>
    <Li class="py-2">Autism SA (2023). *Autism first signs: a checklist for primary school age children*. https://thespectrum.org.au/autism-diagnosis/checklist-primary-school/</Li>
    <Li class="py-2">Autism Spectrum Australia (2023). *What is autism?* . https://www.autismspectrum.org.au/about-autism/what-is-autism</Li>
    <Li class="py-2">Bojanek, E. K., Wang, Z., White, S. P., & Mosconi, M. W. (2020). Postural control processes during standing and step initiation in autism spectrum disorder. *Journal of Neurodevelopmental Disorders*, *12*(1), 1. https://doi.org/10.1186/s11689-019-9305-x</Li>
    <Li class="py-2">Burns, J., & Johnston, M. (2023). *Good Practice Guide for coaching athletes with Intellectual Disabilities*. IDEAL. https://thevirtusacademy.com/wp-content/uploads/2021/05/1B.-IDEAL-Good-Practice-Guide-Sports-Coaching.pdf</Li>
    <Li class="py-2">Cooper, K., Smith, L. G. E., & Russell, A. (2017). Social identity, self-esteem, and mental health in autism. *European Journal of Social Psychology*, *47*(7), 844-854. [https://doi.org/https://doi.org/10.1002/ejsp.2297](https://doi.org/https:/doi.org/10.1002/ejsp.2297)</Li>
    <Li class="py-2">Flygare Wallén, E., Ljunggren, G., Carlsson, A. C., Pettersson, D., & Wändell, P. (2018). High prevalence of diabetes mellitus, hypertension and obesity among persons with a recorded diagnosis of intellectual disability or autism spectrum disorder. *Journal of Intellectual Disability Research*, *62*(4), 269-280. [https://doi.org/https://doi.org/10.1111/jir.12462](https://doi.org/https:/doi.org/10.1111/jir.12462)</Li>
    <Li class="py-2">Garcia, J. M., Leahy, N., Rivera, P., Renziehausen, J., Samuels, J., Fukuda, D. H., & Stout, J. R. (2020). Brief Report: Preliminary Efficacy of a Judo Program to Promote Participation in Physical Activity in Youth with Autism Spectrum Disorder. *Journal of Autism and Developmental Disorders*, *50*(4), 1418-1424. [https://doi.org/https://doi.org/10.1007/s10803-019-04338-w](https://doi.org/https:/doi.org/10.1007/s10803-019-04338-w)</Li>
    <Li class="py-2">Kimber, A., Burns, J., & Murphy, M. (2023). “It’s all about knowing the young person”: Best practice in coaching autistic athletes. *Sports Coaching Review*, *12*(2), 166-186. https://doi.org/10.1080/21640629.2021.1944527</Li>
    <Li class="py-2">Kujach, S., Chroboczek, M., Jaworska, J., Sawicka, A., Smaruj, M., Winklewski, P., & Laskowski, R. (2022). Judo training program improves brain and muscle function and elevates the peripheral BDNF concentration among the elderly. *Scientific Reports*, *12*(1), 13900. https://doi.org/10.1038/s41598-022-17719-6</Li>
    <Li class="py-2">Lever, A. G., & Geurts, H. M. (2016). Psychiatric Co-occurring Symptoms and Disorders in Young, Middle-Aged, and Older Adults with Autism Spectrum Disorder. *Journal of Autism and Developmental Disorders*, *46*(6), 1916-1930. https://doi.org/10.1007/s10803-016-2722-8</Li>
    <Li class="py-2">Mazefsky, C. A., Herrington, J., Siegel, M., Scarpa, A., Maddox, B. B., Scahill, L., & White, S. W. (2013). The role of emotion regulation in autism spectrum disorder. *J Am Acad Child Adolesc Psychiatry*, *52*(7), 679-688. https://doi.org/10.1016/j.jaac.2013.05.006</Li>
    <Li class="py-2">Morales, J., Fukuda, D. H., Garcia, V., Pierantozzi, E., Curto, C., Martínez-Ferrer, J. O., . . . Guerra-Balic, M. (2021). Behavioural Improvements in Children with Autism Spectrum Disorder after Participation in an Adapted Judo Programme Followed by Deleterious Effects during the COVID-19 Lockdown. *International Journal of Environmental Research and Public Health*, *18*(16), 8515. https://www.mdpi.com/1660-4601/18/16/8515</Li>
    <Li class="py-2">National Autistic Society (2020). *Sport - a guide for sports coaches and clubs* https://www.autism.org.uk/advice-and-guidance/topics/leisure/sports/sports-coaches</Li>
    <Li class="py-2">Neil, L., Olsson, N. C., & Pellicano, E. (2016). The Relationship Between Intolerance of Uncertainty, Sensory Sensitivities, and Anxiety in Autistic and Typically Developing Children. *J Autism Dev Disord*, *46*(6), 1962-1973. https://doi.org/10.1007/s10803-016-2721-9</Li>
    <Li class="py-2">NHS. (2022). *Signs of autism in children*. https://www.nhs.uk/conditions/autism/signs/children/</Li>
    <Li class="py-2">Pan, C.-Y., Tsai, C.-L., Chu, C.-H., Sung, M.-C., Ma, W.-Y., & Huang, C.-Y. (2016). Objectively Measured Physical Activity and Health-Related Physical Fitness in Secondary School-Aged Male Students With Autism Spectrum Disorders. *Physical Therapy*, *96*(4), 511-520. https://doi.org/10.2522/ptj.20140353</Li>
    <Li class="py-2">Pierantozzi, E., Morales, J., Fukuda, D. H., Garcia, V., Gómez, A. M., Guerra-Balic, M., & Carballeira, E. (2022). Effects of a Long-Term Adapted Judo Program on the Health-Related Physical Fitness of Children with ASD. *Int J Environ Res Public Health*, *19*(24). https://doi.org/10.3390/ijerph192416731</Li>
    <Li class="py-2">raisingchildren. (2022). *Stimming: autistic children and teenagers*. https://raisingchildren.net.au/autism/behaviour/common-concerns/stimming-asd#:~:text=help%20with%20stimming-,About%20stimming%20and%20autism,forth%20while%20sitting%20or%20standing</Li>
    <Li class="py-2">Rivera, P., Renziehausen, J., & Garcia, J. M. (2020). Effects of an 8-Week Judo Program on Behaviors in Children with Autism Spectrum Disorder: A Mixed-Methods Approach. *Child Psychiatry and Human Development*, *51*(5), 734-741. [https://doi.org/https://doi.org/10.1007/s10578-020-00994-7](https://doi.org/https:/doi.org/10.1007/s10578-020-00994-7)</Li>
    <Li class="py-2">Rosso, E. G. (2016). Brief Report: Coaching Adolescents with Autism Spectrum Disorder in a School-Based Multi-Sport Program. *Journal of Autism and Developmental Disorders*, *46*(7), 2526-2531. [https://doi.org/https://doi.org/10.1007/s10803-016-2759-8](https://doi.org/https:/doi.org/10.1007/s10803-016-2759-8)</Li>
    <Li class="py-2">Schaffler, M. D., Middleton, L. J., & Abdus-Saboor, I. (2019). Mechanisms of Tactile Sensory Phenotypes in Autism: Current Understanding and Future Directions for Research. *Curr Psychiatry Rep*, *21*(12), 134. https://doi.org/10.1007/s11920-019-1122-0</Li>
</List>
</div>